# Adapted from Shaun Zhu's comment on https://mateuscosta.me/rust-releases-with-github-actions

name: release

on:
  push:
    tags: 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: release ${{ github.ref }}
        draft: false
        prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
  upload_assets:
    env:
      REPO_NAME: lazycli
    needs: create_release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ${{ REPO_NAME }}
            asset_name: ${{ REPO_NAME }}-linux-x64.tar.gz
          - os: macos-latest
            artifact_name: ${{ REPO_NAME }}
            asset_name: ${{ REPO_NAME }}-darwin-x64.tar.gz
          - os: windows-latest
            artifact_name: ${{ REPO_NAME }}.exe
            asset_name: ${{ REPO_NAME }}-win-x64.tar.gz
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout the source code
      uses: actions/checkout@v2
    - name: build (release)
      run: cargo build --verbose --release
    - name: compress
      uses: master-atul/tar-action@v1.0.2
      with:
        command: c
        cwd: ./target/release
        files: |
          ${{ matrix.artifact_name }}
        outPath: ./target/release/${{ matrix.asset_name }}
    - name: upload release assets
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./target/release/${{ matrix.asset_name }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: application/tar+gzip
